version: '2'

services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
    links:
      - "db:db"
  db:
    image: mysql:5.7.17
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test180422_development